# Generated by Django 4.1.3 on 2022-11-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_crud', '0002_attendances_active_events_active_events_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_password',
            new_name='password',
        ),
    ]
